name: FB Post Group

on:
  workflow_dispatch:

  #schedule:
  #  - cron: "0 9 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Group Bot
        run: node dasboard/index.js group
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

      - name: Upload recordings
        uses: actions/upload-artifact@v4
        with:
          name: recordings
          path: recording_*.mp4

      - name: Commit dasboard update
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add dasboard/data.json
          git commit -m "Update dashboard data" || echo "No changes"
          git push
